/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package upgraded.engine;

import java.util.List;
import java.util.LinkedList;
import java.util.ArrayList;

/**
 * This file represents a configuration of a specific workflow, this might just be temporary
 */
public class App {
    
    public static void main(String[] args) throws InterruptedException {
        
        Counter<String> counter = new Counter<>();  

        ProcessorWorker dryer1 = new ProcessorWorker(List.of(counter), 28800, 5);
        ProcessorWorker dryer2 = new ProcessorWorker(List.of(counter), 28800, 5);
        ProcessorWorker dryer3 = new ProcessorWorker(List.of(counter), 28800, 5); 

        ProcessorWorker peeler = new ProcessorWorker(List.of(dryer1, dryer2, dryer3), 20, 1);
        ProcessorWorker deseeder = new ProcessorWorker(List.of(peeler), 5, 1);

        Manager manager = new Manager(List.of(counter, dryer1, dryer2, dryer3, peeler, deseeder), 
            () -> counter.getCount() >= 1000);

        for (int i=0; i<1000; i++) {
            deseeder.addWorkItem("a");
        }

        manager.run();

        System.out.println("time used: " + manager.getTime());

    }

}
